### ISSUE TITLE
Empty lines throw an index out of range

### ISSUE THREAD

**Issue by ricdotnet** [ricdotnet/goenvironmental#3]
read the title ^

basically leaving empty lines on a .env file will throw an error. need to ignore or trim them away when parsing

**Comment by Arghya721** [comment]
Hi @ricdotnet 

Want to point out that this error is also created if there is some string that does not follow `<string>=<string>` pattern. 

Example : 
```
HELLO=world
THIS=works
NUMBERS=0123456789
TEST5=hello=world
WITHQUOTES="hello world"
hellothere
```

**Comment by ricdotnet** [comment]
@Arghya721 Hi, yes, thank you very much, that is correct :-)

**Comment by Arghya721** [comment]
@ricdotnet  I have got a fix which would first check this pattern and then put it inside the map :-)

**Comment by ricdotnet** [comment]
Thank you. you can open a pr and I'll get it merged eventually. Appreciate your effort! 🥇
